# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Neelima Sharma
# email: neelima.sharma@uchicago.edu 
# email_space: neelima dot sharma at uchicago dot edu
# description: >- # this means to ignore newlines until "baseurl:"

#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: "@42neelima"
# github_username:  

# Basic Site Settings
locale                   : "en-US"
title                    : "About"
title_separator          : "-"
name                     : &name ""
description              : &description "Intrigued by the role of mechanics in organismal development and function."
url                      : https://neelimasharma.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "NeelimaSharma/neelimasharma.github.io"


author:
  name     : "Neelima Sharma"
  avatar   : "" 
  # docs/assets/images/profile.png
  bio      : ""
  location         : "Chicago, US"
  employer         : "University of Chicago"
  uri              : # URL
  email            : "neelima.sharma@uchicago.edu" 
    # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=Qg3qMcsAAAAJ&hl=en"
  # impactstory      : # URL
  orcid            : "https://orcid.org/0000-0002-1631-5918"
  # pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  # researchgate     : # URL
    # Social media
  # bluesky          : "bsky.app" # Replace this with you Bluesky username
  # facebook         : # Username
  # flickr           : # Username
  # foursquare       : # Username
  # goodreads        : # Username
  # google_plus      : # Username
  # keybase          : # Username
  # instagram        : # Username
  # lastfm           : # Username
  linkedin         : neelima-sharma-672376184
  # mastodon         : # URL
  # medium           : # URL
  # pinterest        : # Username
  # soundcloud       : # Username
  # steam            : # Username
  # telegram         : # URL
  # tumblr           : # Username
  bsky          : "neelimasharma@bsky.social"  
  # Replace this with your X / Twitter handle
  # vine             : # Username
  # weibo            : # Username
  # wikipedia        : # Username
  # xing             : # Username
  # youtube          : # Username
  # zhihu            : # URL


# Reading Files
include:
  - .htaccess
  - _pages
  # - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# theme: minimal-mistakes-jekyll
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# remote_theme: pages-themes/tactile@v0.2.0
remote_theme: "jekyll/minima@1e8a445"
layout: single
# minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       # read_time: true
#       # comments: true
#       # share: true
#       related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
#   # _teaching
#   - scope:
#       path: ""
#       type: teaching
#     values:
#       layout: single
#       author_profile: true
#       share: true
#       comments: true
#   # _publications
#   - scope:
#       path: ""
#       type: publications
#     values:
#       layout: single
#       author_profile: true
#       share: true
#       comments: true
#   # _portfolio
#   - scope:
#       path: ""
#       type: portfolio
#     values:
#       layout: single
#       author_profile: true
#       share: true
#       comment: true
#   # _talks
#   - scope:
#       path: ""
#       type: talks
#     values:
#       layout: talk
#       author_profile: true
#       share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  # plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# # Build settings
# markdown: kramdown
# # url: "https://www.neelimasharma.com"
# atom_feed:
#   hide: true
# search: true
# lunr:
#   search_within_pages: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# include:
#   - _redirects
#   - _pages
# # include: ["_pages"]

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
